title: Jack's blog
description: Experiences sharing
author: Jack Deng
avatar: /logo.png #头像
email: 1076623892@qq.com


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6 #每页显示几条博客

 disqus:
 shortname: jack-925

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - https://twitter.com/ngzhio
    - https://www.facebook.com/ngzhio
    - https://github.com/Jack-925
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
